import type { NormalizedInventory, ScanResult } from "@/services/auditor/types";

/* ------------------------------------------------------------------ */
/* Stage 3 — Reconstruction.                                           */
/* Everything below is generated from the REAL normalized inventory.   */
/* ------------------------------------------------------------------ */

export function buildRealReadme(auditName: string, inv: NormalizedInventory, results: ScanResult[]): string {
  const repo = inv.repo as { totalFiles?: number; totalLines?: number; topLevel?: string[]; byExtension?: Record<string, { files: number; lines: number }> };
  const host = inv.host as { node?: string; platform?: string; appMode?: string; nodeEnv?: string };
  const exts = Object.entries(repo.byExtension ?? {})
    .sort((a, b) => b[1].lines - a[1].lines)
    .slice(0, 6);

  /* DB evidence: only claim schema state when the database-inventory scanner
     actually ran and did not fail. Without it, "No missing indexes" would be
     a false-green — an unmeasured DB reported as healthy. */
  const dbScan = results.find((r) => r.scanner === "database-inventory");
  const dbMeasured = !!dbScan && dbScan.status !== "failed";
  const schemaLine = !dbMeasured
    ? "- Database not measured — `TARGET_DATABASE_URL` not configured or scanner failed. Schema/index state unknown."
    : inv.schema.missingIndexes.length
      ? `- Hot columns without index: ${inv.schema.missingIndexes.map((m) => `\`${m.table}.${m.column}\``).join(", ")}`
      : "- No missing indexes detected on hot paths.";

  return `# ${auditName} — Reconstructed System Overview

> Generated by **AI System Auditor** (real scanners) · ${new Date().toISOString()}
> Read-only guarantee: filesystem read, \`information_schema\` SELECT, package metadata parse. No writes, no process spawning.

## 1. Scan summary

| Scanner | Status | Duration | Warnings |
| ------- | ------ | -------- | -------- |
${results.map((r) => `| \`${r.scanner}\` | ${r.status} | ${r.durationMs}ms | ${r.warnings.length} |`).join("\n")}

## 2. Repository inventory (measured)

- Files scanned: **${repo.totalFiles ?? 0}**
- Lines of code/config: **${(repo.totalLines ?? 0).toLocaleString()}**

| Extension | Files | Lines |
| --------- | ----- | ----- |
${exts.map(([ext, v]) => `| \`${ext}\` | ${v.files} | ${v.lines} |`).join("\n")}

### Top-level layout

\`\`\`text
${(repo.topLevel ?? []).join("\n")}
\`\`\`

## 3. Runtime

- Node: \`${host.node ?? "?"}\` on \`${host.platform ?? "?"}\`
- APP_MODE: \`${host.appMode ?? "demo"}\` · NODE_ENV: \`${host.nodeEnv ?? "?"}\`
- Env contract: ${inv.env.present.length}/${inv.env.declared.length} declared variables set${inv.env.missing.length ? ` (missing: ${inv.env.missing.join(", ")})` : ""}

## 4. Service catalog (${inv.services.length} routes)

| Route | Methods | Guarded |
| ----- | ------- | ------- |
${inv.services
  .slice(0, 30)
  .map((s) => {
    const r = s as { route?: string; methods?: string[]; guarded?: boolean };
    return `| \`${r.route}\` | ${(r.methods ?? []).join(", ")} | ${r.guarded ? "yes" : "—"} |`;
  })
  .join("\n")}

## 5. Database schema

${dbMeasured ? `- Tables: **${inv.schema.tables.length}** · Indexes: **${inv.schema.indexes.length}**` : "- Database not measured (scanner skipped or failed)"}
${schemaLine}

| Table | Columns |
| ----- | ------- |
${inv.schema.tables.map((t) => `| \`${t.table}\` | ${t.columns} |`).join("\n")}

## 6. Dependencies

${inv.dependencies.length} declared packages (${inv.dependencies.filter((d) => d.type === "runtime").length} runtime).
Full component list with resolved versions and licenses: \`recon/sbom.cyclonedx.json\`.

## 7. Findings

${inv.findings.map((f) => `- **[${f.severity.toUpperCase()}]** ${f.title} — \`${f.evidence.slice(0, 90)}\``).join("\n")}

## 8. Reproduce

\`\`\`bash
npm run db:push && npm run db:seed   # demo data
APP_MODE=production npm run worker   # real audit engine
\`\`\`
`;
}

export function buildRealSbom(auditName: string, inv: NormalizedInventory): string {
  return JSON.stringify(
    {
      bomFormat: "CycloneDX",
      specVersion: "1.6",
      serialNumber: `urn:uuid:${crypto.randomUUID()}`,
      version: 1,
      metadata: {
        timestamp: new Date().toISOString(),
        tools: [{ vendor: "AI Agent OS", name: "auditor-sbom-export", version: "0.4.0" }],
        component: { type: "application", name: "ai-agent-os", version: "1.0.0" },
        properties: [{ name: "audit", value: auditName }],
      },
      components: inv.dependencies.map((d) => ({
        type: "library",
        "bom-ref": `pkg:npm/${d.name}@${d.version}`,
        name: d.name,
        version: d.version,
        scope: d.type === "runtime" ? "required" : "optional",
        licenses: d.license === "UNKNOWN" ? [] : [{ license: { id: d.license } }],
      })),
    },
    null,
    2,
  );
}

export function buildRealArchitectureMmd(inv: NormalizedInventory): string {
  const groups = new Map<string, string[]>();
  for (const s of inv.services) {
    const r = s as { route?: string; methods?: string[] };
    const seg = (r.route ?? "/api").split("/")[2] ?? "root";
    const list = groups.get(seg) ?? [];
    list.push(`${(r.methods ?? []).join("/")} ${r.route}`);
    groups.set(seg, list);
  }

  return `flowchart LR
  UI[Next.js Control Plane<br/>7 pages]
  MW[middleware<br/>auth gate]
  UI --> MW
${[...groups.entries()]
  .map(([seg, routes], i) => `  MW --> G${i}["/api/${seg}<br/>${routes.length} handler(s)"]`)
  .join("\n")}
  ${[...groups.keys()].map((_, i) => `G${i}`).join(" --> DB\n  ")} --> DB[(PostgreSQL<br/>${inv.schema.tables.length} tables)]
  WK[Worker process<br/>DB queue] --> DB
  AUD[AI System Auditor<br/>read-only] -. SELECT only .-> DB
  AUD -. fs read .-> REPO[(Repository<br/>${(inv.repo as { totalFiles?: number }).totalFiles ?? 0} files)]
`;
}

export function buildRealRunbook(inv: NormalizedInventory, results: ScanResult[]): string {
  const failed = results.filter((r) => r.status !== "success");
  return `# RUNBOOK — reconstructed ${new Date().toISOString().slice(0, 10)}

## 1. Service map

${inv.services.length} HTTP handlers discovered. Mutating endpoints are protected by
\`getActor()\` + \`hasPermission()\`; the edge middleware rejects unauthenticated
mutations before they reach a handler.

## 2. Golden signals

| Signal | Source | Healthy |
| ------ | ------ | ------- |
| p95 latency | \`/api/telemetry/summary\` | ≤ 150 ms |
| Queue depth | \`jobs\` table | < 40 |
| Worker heartbeat | \`jobs.heartbeat_at\` | < 45 s |
| Parity score | \`/api/parity/latest\` | ≥ 95 |

## 3. Recovery from scratch

\`\`\`bash
cp .env.example .env
npm ci                 # requires package-lock.json (${(inv.repo as { lockFilePresent?: boolean }).lockFilePresent ? "present ✓" : "MISSING ✗"})
npm run db:push
npm run db:seed        # demo only — blocked when APP_MODE=production
npm run build && npm run start
APP_MODE=production npm run worker
\`\`\`

## 4. Stuck job recovery

Worker claims with \`FOR UPDATE SKIP LOCKED\` and heartbeats each tick.
If a worker dies, \`requeueStaleJobs()\` returns the job to \`queued\` after 45 s,
or marks it \`timed_out\` once \`attempt >= max_attempts\`.

## 5. Degraded scanners

${failed.length === 0 ? "All scanners returned success at reconstruction time." : failed.map((f) => `- \`${f.scanner}\`: ${f.status}${f.error ? ` — ${f.error}` : ""}`).join("\n")}

## 6. Env contract

Declared: ${inv.env.declared.length} · Set: ${inv.env.present.length}${inv.env.missing.length ? ` · Missing: ${inv.env.missing.join(", ")}` : ""}
`;
}

export function buildInventoryJson(name: string, payload: unknown): string {
  return JSON.stringify({ report: name, generatedAt: new Date().toISOString(), schemaVersion: "1.0", payload }, null, 2);
}
