/* Bundle the external worker (src/worker/index.ts) into a single self-contained
 * JavaScript file that the Tauri desktop shell can run with plain `node` — no
 * tsx, no TypeScript loader, no path aliases at runtime.
 *
 * The worker imports from ../db, ../services/audit, ../services/jobs, etc., and
 * those modules use the `@/` path alias (e.g. `@/db/schema`, `@/lib/version`).
 * esbuild does not natively resolve tsconfig `paths`, so a tiny resolve plugin
 * maps `@/...` → `./src/...` before bundling.
 *
 * Output: dist/worker/index.js (ESM, platform=node, target=node22).
 * All dependencies (pg, drizzle-orm, dotenv, zod, ...) are bundled in. `pg` is
 * pure JS (pg-native is optional and not used by default), so no native addons
 * are needed at runtime.
 *
 * This script is called by `npm run build:worker` and by the Tauri
 * beforeBuildCommand so the compiled worker is always fresh in the installer.
 */
import esbuild from "esbuild";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

/* Resolve `@/foo/bar` → `<root>/src/foo/bar` so esbuild can bundle modules
   that use the tsconfig path alias. */
const aliasPlugin = {
  name: "tsconfig-alias",
  setup(build) {
    /* Intercept `@/foo/bar` imports and re-resolve them as `./src/foo/bar`
       from the project root, so esbuild's built-in resolver handles
       extension resolution (.ts, .js, /index.ts, etc.). */
    build.onResolve({ filter: /^@\// }, async (args) => {
      const rel = args.path.slice(2); /* strip `@/` */
      const result = await build.resolve(`./src/${rel}`, {
        resolveDir: ROOT,
        kind: args.kind,
        importer: args.importer,
      });
      if (result.errors.length > 0) return { errors: result.errors };
      return { path: result.path, external: result.external };
    });
  },
};

try {
  const result = await esbuild.build({
    entryPoints: [path.join(ROOT, "src/worker/index.ts")],
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node22",
    outfile: path.join(ROOT, "dist/worker/index.js"),
    sourcemap: "linked",
    logLevel: "info",
    plugins: [aliasPlugin],
    /* Nothing external — bundle pg, drizzle-orm, dotenv, zod, etc. so the
       worker runs with zero node_modules on the host (only system Node). */
    external: [],
    /* .env files should never be bundled — they're runtime config. */
    loader: { ".env": "empty" },
    banner: {
      js: "/* Auto-generated by scripts/build-worker.mjs — do not edit. */",
    },
  });
  if (result.errors.length === 0) {
    console.log("✓ worker bundled → dist/worker/index.js");
  } else {
    process.exit(1);
  }
} catch (err) {
  console.error("✗ worker bundle failed:", err);
  process.exit(1);
}
